### ISSUE TITLE
[ Request ] Update img to 0.5.6

### ISSUE THREAD

**Issue by Typositoire** [concourse/builder-task#11]
With current version (0.5.1), login to private registry fail with dns queries Oo upgrading to 0.5.6 fixes this issue.

**Comment by vito** [comment]
I've pushed a new image as `concourse/builder-task` (not `concourse/builder`!) with img 0.5.6. :+1:

**Comment by Typositoire** [comment]
Cool! Thanks!

**Comment by Typositoire** [comment]
@vito Actually sorry to bother again... Are you building img yourself ? I can successfully login with the release bin but not with your image.

concourse/builder-task:
![image](https://user-images.githubusercontent.com/721017/55098080-8ac39980-5093-11e9-8bd1-ef7abe95fd67.png)

release bin:
![image](https://user-images.githubusercontent.com/721017/55098096-944d0180-5093-11e9-8625-50ef1a38ed1f.png)

**Comment by vito** [comment]
I'm inheriting from their image, not building it myself: https://github.com/concourse/builder-task/blob/master/Dockerfile

**Comment by Typositoire** [comment]
Oh well Oo I'll just install it over in the image then xD Thanks anyway!

**Comment by vito** [comment]
fwiw this should be up-to-date now:

```
~/workspace/builder-task master*
❯ docker run concourse/builder-task version
img:
 version     : v0.5.6
 git hash    : 013bb211
 go version  : go1.11.7
 go compiler : gc
 platform    : linux/amd64
```
