### ISSUE TITLE
Using with concourse v5+

### ISSUE THREAD

**Issue by yasn77** [concourse/builder-task#14]
Hi,

I am a little unsure how this would work with Concourse v5+ (managed to get it to work with previous versions). When trying to `put` the output, the concourse complains since it is expecting a resource for `put`. As no real resource is created (this is just a task), I am not sure how to share the image across multiple jobs.

Thanks

**Comment by vito** [comment]
To push the image you've built you would use the [`registry-image` resource](https://github.com/concourse/registry-image-resource).
