### ISSUE TITLE
Feature request: support dynamic output path instead of hard-code `image`

### ISSUE THREAD

**Issue by SimonXming** [concourse/builder-task#18]
Could we allow user-defined output for saved image tarball? (Like `params.OUTPUT`)

**Comment by vito** [comment]
Have a look at `output_mapping` for renaming outputs: https://concourse-ci.org/task-step.html#output_mapping

**Comment by SimonXming** [comment]
> Have a look at `output_mapping` for renaming outputs: https://concourse-ci.org/task-step.html#output_mapping

Thanks. I totally forgot that :o ...
