### ISSUE TITLE
Question: Why provide a task instead of a resource-type for image build?

### ISSUE THREAD

**Issue by SimonXming** [concourse/builder-task#19]
Is that possible to provide a resource-type for image building? What's the pros and cons of using `builder-task`? Thanks :)

**Comment by vito** [comment]
Pros:

* The image can be built and then used immediately without having to push it to a registry.
* Separation of concerns - now we've got a task with config for image building, and a [`registry-image` resource](https://github.com/concourse/registry-image-resource) with config for image pushing. This keeps both interfaces smaller and more focused.

Cons:

* The UX for re-usable tasks isn't great right now, forcing most configuration to happen via env vars, which isn't great compared to resource's params JSON. We're planning to improve this with concourse/rfcs#7.
