### ISSUE TITLE
Support for Alternative Tags

### ISSUE THREAD

**Issue by SergueiFedorov** [concourse/builder-task#32]
Our build process requires us to provide a generic tag + unique tag. For instance

     foo:development
     foo:4824be76-0335-4f00-aef8-59c129db289d

which was possible with the `docker-image` `put` using `additional_tags`. I can't replicate this using the `concourse/builder-task` and I'm wondering if there is an approach that allows for this? 

The only way I can think of is to have two `concourse/builder-task` task steps which rely on caching to avoid rebuilding the image (But with different TAG variables)

**Comment by vito** [comment]
This is supported by the `registry-image` resource: https://github.com/concourse/registry-image-resource#out-push-an-image-up-to-the-registry-under-the-given-tags
