### ISSUE TITLE
New lines in BUILD_ARGS_FILE cause empty --build-arg, so build fails

### ISSUE THREAD

**Issue by pidster** [concourse/builder-task#33]
When a file containing key/value pairs is supplied to BUILD_ARGS_FILE, it must not contain empty lines - doing so will cause an empty `--build-arg` parameter to be appended to the command. The build will then fail.

To reproduce, supply the parameter BUILD_ARGS_FILE, with a file containing the following:

```
FOO=bar
BAR=eep

```

(note the extra whitespace)

**Comment by vito** [comment]
fixed by #34
