### ISSUE TITLE
How to push an image by tag?

### ISSUE THREAD

**Issue by dhonig** [concourse/builder-task#36]
I have the following definitions in the gist:
https://gist.github.com/dhonig/566354a1b23974819b1eb0c456b6a70e

What I am attempting to do is to store the GIT commit SHA in combined-sources and then push the image by the git commit sha.

So early on in my build I write the sha to combined-sources/tmp/commit.txt 
The image should be built by this tag with 
    params:
            REPOSITORY: dhonig/my-api
            TAG_FILE: combined-sources/tmp/commit.txt
            CONTEXT: combined-sources

But I only see "latest" in the logs:

	
building
18:25:54 Building docker.io/dhonig/my-api:latest
18:25:54 Setting up the rootfs... this may take a bit.
18:25:55  25l[+] Building 228.6s (30/30) FINISHED             

What I would expect is that the image is being built with the contents of combined-sources/tmp/commit.txt

How can I read the commit sha in from a file and then push that tag back out using the registry-image-resource?

**Comment by vito** [comment]
Gonna close this as the new [`oci-build` task](https://github.com/vito/oci-build-task) is replacing this one and no longer supports tagging - that should be a concern of the `registry-image` resource instead.
