### ISSUE TITLE
error: "failed calculating diff pairs for exported snapshot

### ISSUE THREAD

**Issue by jk21** [concourse/builder-task#37]
Hi,

when using the build-task i am getting the following error in the last step:

```
#12 exporting to image

#12       digest:
sha256:0be3e8ffcff73e71831a5c7e63ba0124fc0fc779b08a6f8a49a1af9b94eea7af

#12         name: "exporting to image"

#12      started: 2019-08-05 12:14:57.909369453 +0000 UTC m=+63.845516601	

#12 exporting layers

#12    completed: 2019-08-05 12:15:01.400674152 +0000 UTC m=+67.336821294

#12     duration: 3.491304693s

#12        error: "failed calculating diff pairs for exported snapshot: mount callback failed on /run/user/1000/containerd-mount895903867: mount callback failed on /run/user/1000/containerd-mount431519333: failed to write compressed diff: failed to create diff tar stream: stat /run/user/1000/containerd-mount431519333/opt/app/node_modules/ansi: no such file or directory"
```

any ideas? is it an upstream error in https://github.com/genuinetools/img ?

**Comment by vito** [comment]
No clue, sorry. It's probably an issue upstream; there's not a whole lot going on in our own code. Does building the same image fail with Docker?

**Comment by davidhole** [comment]
If it helps, I had a _RUN npm prune --production_ line in my Dockerfile, which was causing this error. As soon as I removed this line, the build succeeded...

Although the same Dockerfile works fine when built with docker

YMMV :)

**Comment by vito** [comment]
Gonna close this since it seems like an upstream issue we can't really do anything about. You could try again with the [`oci-build` task](https://github.com/vito/oci-build-task) which replaces this task.

**Comment by jk21** [comment]
> If it helps, I had a _RUN npm prune --production_ line in my Dockerfile, which was causing this error. As soon as I removed this line, the build succeeded...
> 
> Although the same Dockerfile works fine when built with docker
> 
> YMMV :)

I am also using npm prune --production, thanks for the help. I will try with the new task some time.
