### ISSUE TITLE
Are we rootless yet?

### ISSUE THREAD

**Issue by cirocosta** [concourse/builder-task#8]
Hey,

It's stated that `builder` has the stretch goal of running without the need of `privileged: true`, and looking at [img#upstream-patches](https://github.com/genuinetools/img#upstream-patches), it feels like the base functionality is already there at `runc` level, with only the Docker CLI missing in terms of catching up with the functionality.

What does that mean for us, having the `garden` interface between ourselves and runc?

Are there specific issues that we could track to know how far we are from having this not running with `privileged: true`?

Thanks!

**Comment by vito** [comment]
Last time I tried it I ran into trouble; iirc `img` still requires something which Garden doesn't grant for unprivileged containers.

Haven't had time to try again. We might need to ask Garden folks for help here.

**Comment by databus23** [comment]
I tried this again and when skipping the `sanitize_cgroups` functions which try to remount stuff that is forbidden this is the error that pops up from `img` in an unprivileged task:
```
/tmp/build/e55deab7 # img build -d -s /scratch/state -t databus23/builder-test:test -f builder/Dockerfile builder
nsenter: failed to unshare namespaces: Operation not permitted
```

Which I believe comes from here: https://github.com/genuinetools/img/blob/641582df8270d99b4db0ed164ed0386168003864/internal/unshare/unshare.c#L453-L454

**Comment by vito** [comment]
The new [`oci-build` task](https://github.com/vito/oci-build-task) theoretically supports rootless builds, but we're still dependent on Garden which seems to prohibit it. This may change in the future when we switch to k8s/`containerd`.

Gonna close this since this repo will be phased out in favor of the new task.
