### ISSUE TITLE
Unable to use behind firewall

### ISSUE THREAD

**Issue by jonahgeorge** [concourse/builder-task#9]
It appears that `img` reaches out to Docker Hub during the build task:

```sh
failed to solve: failed to do request: Head https://registry-1.docker.io/v2/tonistiigi/copy/manifests/sha256:d9d49bedbbe2b27df88115e6aff7b9cd11ed2fbd8d9013f02d3da735c08c92e5: dial tcp 34.200.28.105:443: connect: no route to host
```

Related:
- https://github.com/genuinetools/img/issues/165
- https://github.com/moby/buildkit/issues/706

**Comment by vito** [comment]
Yeah, this is hurting me too. I'd really like to be able to use something like the `docker-image` resource's `load_base`/`load_bases`. Seems like we're limited by upstream right now.

**Comment by vito** [comment]
Closing out this repo soon in favor of the new [`oci-build` task](https://github.com/vito/oci-build-task). The corresponding issue tracking this is https://github.com/vito/oci-build-task/issues/1
